"""refactor_report_templates

Revision ID: 0e978eb56976
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 21:53:15.632709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e978eb56976'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_school_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_school_history_school_id'), 'student_school_history', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_school_history_student_id'), 'student_school_history', ['student_id'], unique=False)
    op.add_column('report_templates', sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report_templates', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('report_templates', 'secoes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_report_templates_tipo'), table_name='report_templates')
    op.create_index(op.f('ix_report_templates_nome'), 'report_templates', ['nome'], unique=False)
    op.drop_column('report_templates', 'tipo')
    op.add_column('reports', sa.Column('template_id', sa.Uuid(), nullable=False))
    op.alter_column('reports', 'template_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reports', 'conteudo_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_reports_tipo'), table_name='reports')
    op.create_index(op.f('ix_reports_template_id'), 'reports', ['template_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'report_templates', ['template_id'], ['id'])
    op.drop_column('reports', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('tipo', postgresql.ENUM('AEE', 'ANUAL', 'TRIMESTRAL', name='tiporelatorio'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_template_id'), table_name='reports')
    op.create_index(op.f('ix_reports_tipo'), 'reports', ['tipo'], unique=False)
    op.alter_column('reports', 'conteudo_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reports', 'template_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('reports', 'template_id')
    op.add_column('report_templates', sa.Column('tipo', postgresql.ENUM('AEE', 'ANUAL', 'TRIMESTRAL', name='tiporelatorio'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_report_templates_nome'), table_name='report_templates')
    op.create_index(op.f('ix_report_templates_tipo'), 'report_templates', ['tipo'], unique=False)
    op.alter_column('report_templates', 'secoes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('report_templates', 'descricao')
    op.drop_column('report_templates', 'nome')
    op.drop_index(op.f('ix_student_school_history_student_id'), table_name='student_school_history')
    op.drop_index(op.f('ix_student_school_history_school_id'), table_name='student_school_history')
    op.drop_table('student_school_history')
    # ### end Alembic commands ###
