"""add escola_id to user

Revision ID: b7d8c9a0e1f2
Revises: f1a2b3c4d5e6
Create Date: 2026-06-22 23:20:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b7d8c9a0e1f2'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('escola_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_escola_id'), 'users', ['escola_id'], unique=False)
    op.create_foreign_key(None, 'users', 'schools', ['escola_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_escola_id'), table_name='users')
    op.drop_column('users', 'escola_id')
    # ### end Alembic commands ###
