"""Add schedules table

Revision ID: e6630838985b
Revises: 0e978eb56976
Create Date: 2026-06-16 23:29:46.627507

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6630838985b'
down_revision: str | Sequence[str] | None = '0e978eb56976'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atividade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_aluno_id'), 'schedules', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_aluno_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
