"""Initial schema

Revision ID: ef9a0507274f
Revises: 
Create Date: 2026-03-31 17:31:01.580317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef9a0507274f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('field_accessed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_student_id'), 'audit_log', ['student_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tag', sa.Enum('AUTONOMIA', 'COMUNICACAO', 'MOTOR_FINO', 'SOCIALIZACAO', 'OUTRO', name='tagpedagogica'), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_aluno_id'), 'photos', ['aluno_id'], unique=False)
    op.create_table('professor_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('escola_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_papel', sa.Enum('COORDENACAO', 'PROF_AEE', 'PROF_APOIO', 'PROF_REGENTE', name='papelusuario'), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professor_assignments_aluno_id'), 'professor_assignments', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_professor_assignments_escola_id'), 'professor_assignments', ['escola_id'], unique=False)
    op.create_index(op.f('ix_professor_assignments_usuario_id'), 'professor_assignments', ['usuario_id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('AEE', 'ANUAL', 'TRIMESTRAL', name='tiporelatorio'), nullable=False),
    sa.Column('secoes', sa.JSON(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_tipo'), 'report_templates', ['tipo'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('AEE', 'ANUAL', 'TRIMESTRAL', name='tiporelatorio'), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Uuid(), nullable=False),
    sa.Column('template_snapshot', sa.JSON(), nullable=True),
    sa.Column('conteudo_json', sa.JSON(), nullable=True),
    sa.Column('travado', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.Enum('LOCAL', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_aluno_id'), 'reports', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_reports_tipo'), 'reports', ['tipo'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_tenant_id'), 'schools', ['tenant_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('escola_atual_id', sa.Uuid(), nullable=True),
    sa.Column('diagnostico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('laudo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False),
    sa.Column('data_consentimento', sa.DateTime(), nullable=True),
    sa.Column('base_legal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'ARQUIVADO', name='statusaluno'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('papel', sa.Enum('COORDENACAO', 'PROF_AEE', 'PROF_APOIO', 'PROF_REGENTE', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_schools_tenant_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_reports_tipo'), table_name='reports')
    op.drop_index(op.f('ix_reports_aluno_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_report_templates_tipo'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_professor_assignments_usuario_id'), table_name='professor_assignments')
    op.drop_index(op.f('ix_professor_assignments_escola_id'), table_name='professor_assignments')
    op.drop_index(op.f('ix_professor_assignments_aluno_id'), table_name='professor_assignments')
    op.drop_table('professor_assignments')
    op.drop_index(op.f('ix_photos_aluno_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_student_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
